# Generated by Django 4.1 on 2023-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_alter_appointment_status_servicecartmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecartmodel',
            name='bought_status',
            field=models.BooleanField(default=False),
        ),
    ]
