# Generated by Django 4.2.1 on 2023-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
